/**
 * Sound, synthesised.
 *
 * There was none at all, which is why the horn did nothing you could hear.
 * Every sound here is generated by the Web Audio API rather than loaded — no
 * files to ship, nothing for the CSP to allow, and a two-tone horn is four
 * oscillators rather than a 40 kB mp3.
 *
 * Browsers refuse to start an AudioContext without a gesture. Rides always
 * begin from a tap, so by the time this is constructed the gesture has
 * happened; if it has not, everything here degrades to silence rather than
 * throwing.
 */

export interface RideAudio {
  /** Engine pitch follows speed, 0 to 1. */
  setSpeed: (speed: number) => void;
  horn: (on: boolean) => void;
  crash: () => void;
  hit: () => void;
  pickup: () => void;
  stop: () => void;
}

const SILENT: RideAudio = {
  setSpeed: () => {},
  horn: () => {},
  crash: () => {},
  hit: () => {},
  pickup: () => {},
  stop: () => {},
};

export function createAudio(): RideAudio {
  const Ctor =
    typeof window === "undefined"
      ? undefined
      : window.AudioContext ??
        (window as unknown as { webkitAudioContext?: typeof AudioContext }).webkitAudioContext;
  if (!Ctor) return SILENT;

  let ctx: AudioContext;
  try {
    ctx = new Ctor();
  } catch {
    return SILENT;
  }

  const master = ctx.createGain();
  master.gain.value = 0.32;
  master.connect(ctx.destination);

  /* ------------------------------------------------------------- engine */

  // A small engine is two detuned saws and a lot of low-pass. Pitch tracks
  // speed, so the ear knows how fast it is going without looking.
  const engineGain = ctx.createGain();
  engineGain.gain.value = 0;
  const engineFilter = ctx.createBiquadFilter();
  engineFilter.type = "lowpass";
  engineFilter.frequency.value = 900;
  engineGain.connect(engineFilter).connect(master);

  const oscA = ctx.createOscillator();
  const oscB = ctx.createOscillator();
  oscA.type = "sawtooth";
  oscB.type = "square";
  oscA.connect(engineGain);
  oscB.connect(engineGain);
  oscA.start();
  oscB.start();

  /* --------------------------------------------------------------- horn */

  // Indian horns are two notes at once and slightly sour. That sourness is the
  // whole character, so the interval is deliberately not clean.
  const hornGain = ctx.createGain();
  hornGain.gain.value = 0;
  hornGain.connect(master);

  const hornA = ctx.createOscillator();
  const hornB = ctx.createOscillator();
  hornA.type = "sawtooth";
  hornB.type = "sawtooth";
  hornA.frequency.value = 440;
  hornB.frequency.value = 554;
  hornA.connect(hornGain);
  hornB.connect(hornGain);
  hornA.start();
  hornB.start();

  let honking = false;

  /* -------------------------------------------------------------- hits */

  /** A burst of filtered noise: what every impact in this game is made of. */
  const burst = (duration: number, freq: number, gain: number, type: BiquadFilterType): void => {
    const frames = Math.floor(ctx.sampleRate * duration);
    const buffer = ctx.createBuffer(1, frames, ctx.sampleRate);
    const data = buffer.getChannelData(0);
    for (let i = 0; i < frames; i++) {
      // Decay the noise as it goes, so it reads as a knock rather than a hiss.
      data[i] = (Math.random() * 2 - 1) * (1 - i / frames) ** 2;
    }

    const src = ctx.createBufferSource();
    src.buffer = buffer;
    const filter = ctx.createBiquadFilter();
    filter.type = type;
    filter.frequency.value = freq;
    const g = ctx.createGain();
    g.gain.value = gain;
    src.connect(filter).connect(g).connect(master);
    src.start();
  };

  const tone = (freq: number, duration: number, gain: number): void => {
    const osc = ctx.createOscillator();
    const g = ctx.createGain();
    osc.type = "triangle";
    osc.frequency.setValueAtTime(freq, ctx.currentTime);
    g.gain.setValueAtTime(gain, ctx.currentTime);
    g.gain.exponentialRampToValueAtTime(0.0001, ctx.currentTime + duration);
    osc.connect(g).connect(master);
    osc.start();
    osc.stop(ctx.currentTime + duration);
  };

  return {
    setSpeed(speed) {
      if (ctx.state === "suspended") void ctx.resume();
      const now = ctx.currentTime;
      const base = 58 + speed * 155;
      oscA.frequency.setTargetAtTime(base, now, 0.08);
      oscB.frequency.setTargetAtTime(base * 0.5, now, 0.08);
      engineFilter.frequency.setTargetAtTime(500 + speed * 1700, now, 0.1);
      engineGain.gain.setTargetAtTime(0.035 + speed * 0.05, now, 0.1);
    },

    horn(on) {
      if (on === honking) return;
      honking = on;
      const now = ctx.currentTime;
      // Short ramps, because a horn that fades in sounds like a foghorn.
      hornGain.gain.setTargetAtTime(on ? 0.16 : 0, now, on ? 0.012 : 0.05);
    },

    crash() {
      burst(0.42, 320, 0.55, "lowpass");
      tone(110, 0.3, 0.18);
    },

    hit() {
      burst(0.16, 1800, 0.4, "bandpass");
    },

    pickup() {
      tone(880, 0.1, 0.12);
      window.setTimeout(() => tone(1320, 0.14, 0.1), 80);
    },

    stop() {
      try {
        oscA.stop();
        oscB.stop();
        hornA.stop();
        hornB.stop();
        void ctx.close();
      } catch {
        // Already torn down; nothing to do.
      }
    },
  };
}
